route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: *email-to-send-message
    from: *email-message-is-sent-from
    smarthost: smtp.gmail.com:587
    auth_username: *email-message-is-sent-from
    auth_identity: *email-message-is-sent-from
    auth_password: *email-password