global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'node_exporter'
    ec2_sd_configs:
      - region: us-east-1
        access_key: *access-key
        secret_key: *secret-key
        port: 9100
  
# Access key and Secret key should originate from;
# configured IAM User with programmatic access and "AmazonEC2ReadOnlyAccess" permission.
#               or
# configure role with "AmazonEC2ReadOnlyAccess" and attach role (advised for production environment).
# but since it only temporary setup, IAM User with programmatic access and "AmazonEC2ReadOnlyAccess" permission was used.
